<a href="https://colab.research.google.com/github/kavyareddy01/pytorchbirble/blob/main/day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
print("I am wish to learn pytorch")

I am wish to learn pytorch


In [71]:
import torch
print(torch.__version__)

2.1.0+cu121


In [72]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [73]:
#tensor
#scalar
s=torch.tensor(7)
s

tensor(7)

In [74]:

s.ndim

0

In [75]:
#get tensor back as python int
s.item()

7

In [76]:
#vector
v=torch.tensor([9,9])
v

tensor([9, 9])

In [77]:
v.ndim


1

In [78]:
v.shape

torch.Size([2])

In [79]:
##matrix
m=torch.tensor([[7,6],[9,8]])
m

tensor([[7, 6],
        [9, 8]])

In [80]:
m.shape


torch.Size([2, 2])

In [81]:
m.ndim


2

In [82]:
m[0]

tensor([7, 6])

In [83]:
m[1]

tensor([9, 8])

In [84]:
#tensor
t=torch.tensor([[[1,2,3],[2,3,4],[3,4,5]]])
t

tensor([[[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]]])

In [85]:
t.shape

torch.Size([1, 3, 3])

In [86]:
t.ndim

3

In [87]:
t[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [88]:
# @title Intro to tensors


In [89]:
t_rand=torch.rand(3,4)
t_rand

tensor([[0.2474, 0.9073, 0.6020, 0.1150],
        [0.3337, 0.5811, 0.4446, 0.5521],
        [0.0986, 0.9296, 0.7449, 0.1014]])

In [90]:
t_rand.ndim

2

In [91]:
rand_t=torch.rand(1,10,10)
rand_t

tensor([[[0.0054, 0.2773, 0.1639, 0.2758, 0.9774, 0.2571, 0.3035, 0.5451,
          0.7002, 0.4523],
         [0.3759, 0.1102, 0.0661, 0.7698, 0.7568, 0.8294, 0.7281, 0.5463,
          0.7003, 0.5099],
         [0.6035, 0.6415, 0.8001, 0.5678, 0.8036, 0.3607, 0.6412, 0.1212,
          0.1631, 0.3641],
         [0.1746, 0.0063, 0.6225, 0.4183, 0.9825, 0.7933, 0.8632, 0.9049,
          0.6525, 0.0539],
         [0.3126, 0.6132, 0.3169, 0.6522, 0.8164, 0.0268, 0.5237, 0.8690,
          0.4400, 0.2274],
         [0.6546, 0.2306, 0.3898, 0.9737, 0.5397, 0.2901, 0.1281, 0.1828,
          0.5287, 0.0664],
         [0.7464, 0.1218, 0.5451, 0.6231, 0.0717, 0.6561, 0.1602, 0.3393,
          0.0639, 0.6486],
         [0.0171, 0.8274, 0.5297, 0.5600, 0.2568, 0.2102, 0.2236, 0.3918,
          0.1070, 0.7522],
         [0.0871, 0.1272, 0.0498, 0.6905, 0.5193, 0.4676, 0.3459, 0.0139,
          0.3453, 0.7926],
         [0.4137, 0.1858, 0.9460, 0.7002, 0.8942, 0.6725, 0.4391, 0.5184,
          0.8224,

In [92]:
rand_t.ndim

3

In [93]:
r_i_s_tensor=torch.rand(size=(224,224,3))#height,width,color channels(R,G,B)
r_i_s_tensor.shape,r_i_s_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [94]:
r_i_s_tensor

tensor([[[0.9936, 0.7277, 0.5937],
         [0.8702, 0.1155, 0.8682],
         [0.5205, 0.6310, 0.2486],
         ...,
         [0.1125, 0.0567, 0.4111],
         [0.1086, 0.5832, 0.0192],
         [0.4324, 0.5460, 0.7356]],

        [[0.6291, 0.7029, 0.7949],
         [0.9400, 0.7565, 0.7533],
         [0.5600, 0.8527, 0.6291],
         ...,
         [0.7810, 0.7008, 0.1706],
         [0.0779, 0.5858, 0.4216],
         [0.6525, 0.6579, 0.8585]],

        [[0.1531, 0.3153, 0.0904],
         [0.3849, 0.9134, 0.9370],
         [0.6198, 0.9523, 0.4780],
         ...,
         [0.7514, 0.4041, 0.2523],
         [0.6634, 0.7363, 0.9042],
         [0.4730, 0.6450, 0.4778]],

        ...,

        [[0.3382, 0.7579, 0.5058],
         [0.8005, 0.7698, 0.5180],
         [0.9848, 0.1183, 0.5320],
         ...,
         [0.6524, 0.0960, 0.9238],
         [0.4430, 0.9918, 0.1104],
         [0.0571, 0.1835, 0.1560]],

        [[0.6604, 0.0465, 0.9704],
         [0.7238, 0.8268, 0.2212],
         [0.

In [95]:
torch.rand(3,3)

tensor([[0.2724, 0.5400, 0.0597],
        [0.4045, 0.0716, 0.4386],
        [0.4905, 0.9647, 0.4392]])

In [96]:
##zeros and ones tensors

z=torch.zeros(size=(3,4))
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [97]:
z*t_rand

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [98]:
o=torch.ones(size=(3,4))
o

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [99]:
o.dtype

torch.float32

In [100]:
rand_t.dtype

torch.float32

In [101]:
t_rand.dtype

torch.float32

In [102]:
z.dtype

torch.float32

In [103]:
##creating a range of tensors
torch.range(0,10)

<ipython-input-103-df6a2ff44385>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [104]:
torch.__version__

'2.1.0+cu121'

In [105]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
one_to_ten=torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
torch.arange(start=1,end=1000,step=77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [108]:
torch.arange(start=1,end=11,step=1)##end is exclusive

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
ten_0s=torch.zeros_like(input=one_to_ten)
ten_0s

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])