<a href="https://colab.research.google.com/github/kavyareddy01/pytorchbirble/blob/main/day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##tensor datatypes

In [3]:
import torch
print(torch.__version__)

2.1.0+cu121


In [4]:
float_32_tensor=torch.tensor([3.0,5.0,10.0],dtype=None)
float_32_tensor

tensor([ 3.,  5., 10.])

In [5]:
float_32_tensor.dtype  ##default

torch.float32

In [6]:
float_32_t=torch.tensor([3.0,5.0,10.0],dtype=torch.float16)
float_32_t

tensor([ 3.,  5., 10.], dtype=torch.float16)

In [7]:
float_32_t.dtype

torch.float16

In [8]:
f=torch.tensor([1.0,2.0,3.0],dtype=None,# what datatype  is the tensor
                            device=None,#what device is ur tensor on
                            requires_grad=False  )#whether or not to track gradients with this tensors operatns
##tensor imp parameters
f
##32-bit floating point->torch.float or torch.float32
#64-bit floating point ->torch.float64 or torch.double
#16-bit floating point ->torch.float16 or torch.half

tensor([1., 2., 3.])

tensor datatypes are the 3 big errors you will run into with pytorch or deeplearning

* tensors not right datatype
* tensors not right shape
* tensors not on the right device

In [9]:
f_16_t=float_32_t.type(torch.float16)
f_16_t

tensor([ 3.,  5., 10.], dtype=torch.float16)

In [10]:
f_16_t*float_32_t

tensor([  9.,  25., 100.], dtype=torch.float16)

In [11]:
float_32_t*f_16_t

tensor([  9.,  25., 100.], dtype=torch.float16)

In [12]:
int_32_tensor=torch.tensor([1,3,6],dtype=torch.int32)
int_32_tensor

tensor([1, 3, 6], dtype=torch.int32)

In [13]:
float_32_t*int_32_tensor

tensor([ 3., 15., 60.], dtype=torch.float16)

In [14]:
int_64_tensor=torch.tensor([1,3,6],dtype=torch.int64)
int_64_tensor

tensor([1, 3, 6])

In [15]:
float_32_t*int_64_tensor

tensor([ 3., 15., 60.], dtype=torch.float16)

In [16]:
long=torch.tensor([4,5,6],dtype=torch.long)
long

tensor([4, 5, 6])

In [17]:
long*float_32_t

tensor([12., 25., 60.], dtype=torch.float16)

GETTING TENSOR ATTRIBUTES(INFO ABOUT TENSORS)

* tensors not right datatype=toget data type from tensor,can use 'tensor.dtype'

* tensors not right shape=to get shape of tensor,can use'tensor.shape'

* tensors not on the right device=to get device from a tensor,can use 'tensor.device'


In [18]:
##creating a tensor
some=torch.rand(3,4)
some

tensor([[0.6835, 0.6890, 0.2582, 0.5567],
        [0.0741, 0.5399, 0.1617, 0.4927],
        [0.3271, 0.0409, 0.3751, 0.2274]])

In [19]:
some.dtype

torch.float32

In [20]:
some.shape

torch.Size([3, 4])

In [21]:
some.device

device(type='cpu')

In [22]:
some.size()##function

torch.Size([3, 4])

In [23]:
print(some)
print(f"datatype of tensor : {some.dtype}")
print(f"size of tensor : {some.size()}")
print(f"shape of tensor : {some.shape}")
print(f"device of tensor : {some.device}")

tensor([[0.6835, 0.6890, 0.2582, 0.5567],
        [0.0741, 0.5399, 0.1617, 0.4927],
        [0.3271, 0.0409, 0.3751, 0.2274]])
datatype of tensor : torch.float32
size of tensor : torch.Size([3, 4])
shape of tensor : torch.Size([3, 4])
device of tensor : cpu


MANIPULATING TENSORS AND TENSORS OPERATNS tensor operatns include

* addition
* subtraction
* multiplicatn(element wise)
* division
* matrix multipilcatn


In [24]:
#create tensor
tensor=torch.tensor([2,3,4])
tensor+10

tensor([12, 13, 14])

In [25]:
tensor+100



tensor([102, 103, 104])

In [26]:
tensor*10

tensor([20, 30, 40])

In [27]:
tensor

tensor([2, 3, 4])

In [28]:
tensor-10

tensor([-8, -7, -6])

In [29]:
#pytorch in built functns
torch.mul(tensor,10)

tensor([20, 30, 40])

In [30]:
torch.add(tensor,120)

tensor([122, 123, 124])

There are two ways o performing matrix multiplicatn in neural networks and deeplearning
* element wise multiplicatn
* matrix Multiplictan(dot product)

In [31]:
# element wise
tensor*tensor

tensor([ 4,  9, 16])

In [32]:
print(tensor,"*",tensor)

tensor([2, 3, 4]) * tensor([2, 3, 4])


In [33]:
print(f"equals :{tensor*tensor}")

equals :tensor([ 4,  9, 16])


In [34]:
##matrix multiplication
torch.matmul(tensor,tensor) #2*2+3*3+4*4


tensor(29)

In [38]:
%%time
val=0
for i in range(len(tensor)):
    val+=tensor[i]*tensor[i]
print(val)

tensor(29)
CPU times: user 2 ms, sys: 946 µs, total: 2.94 ms
Wall time: 3.03 ms


In [40]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 508 µs, sys: 0 ns, total: 508 µs
Wall time: 390 µs


tensor(29)

In [41]:
tensor@tensor

tensor(29)

Two main rules of matrix multipilcation
* inner dimensions should match
     1.  '(4,5)@(4,5)' it don't work
     2.  '(4,5)@(5,4)' it works
* the resulting matrix has outer dimensions



In [42]:
torch.matmul(torch.rand(3,4),torch.rand(4,3))

tensor([[0.8254, 0.3942, 1.0549],
        [0.8478, 0.8562, 1.8058],
        [1.5228, 0.8630, 2.0422]])

In [43]:
torch.matmul(torch.rand(10,10),torch.rand(10,9)).shape

torch.Size([10, 9])

one of the most commom errors in deeplearning is shape errors

In [44]:
t1=torch.tensor([[1,2],[2,3],[3,4]])
t2=torch.tensor([[3,4],[4,5],[5,6]])
##torch.mm is same as torch.matmultiply
torch.mm(t1,t2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [45]:
t1.shape,t2.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [46]:
###to fix tensor shape issues we can manipulate one of the tensors using a **transpose**

### A **transpose** switches the axes or the dimensions of the given tensor  -->tensor.T  gives transpose of tensor

In [47]:
t2.T,t2

(tensor([[3, 4, 5],
         [4, 5, 6]]),
 tensor([[3, 4],
         [4, 5],
         [5, 6]]))

In [48]:
torch.matmul(t1,t2.T)

tensor([[11, 14, 17],
        [18, 23, 28],
        [25, 32, 39]])

In [49]:
t1.shape,t2.shape,t2.T.shape

(torch.Size([3, 2]), torch.Size([3, 2]), torch.Size([2, 3]))

In [51]:
print(f"Original shapes: t1 = {t1.shape}, t2 = {t2.shape}\n")
print(f"New shapes: t1= {t1.shape} (same as above), t2.T = {t2.T.shape}\n")
print(f"Multiplying: {t1.shape} * {t2.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(t1, t2.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: t1 = torch.Size([3, 2]), t2 = torch.Size([3, 2])

New shapes: t1= torch.Size([3, 2]) (same as above), t2.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[11, 14, 17],
        [18, 23, 28],
        [25, 32, 39]])

Output shape: torch.Size([3, 3])


Finding min ,max,sum,mean (TENSOR AGGREGATION)