<a href="https://colab.research.google.com/github/kavyareddy01/pytorchbirble/blob/main/pytorchworkflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PYTORCK WORKFLOW

1. data (prepare and load)
2. "build model"
3. fitting the model to the data(training)
4. make predictns and evaluate a model(inference)
5. saving and loading a model
6. putting all **together**

In [1]:
import torch
from torch import nn # nn contains all of PyTorch's building blocks for neural networks
import matplotlib.pyplot as plt
torch.__version__

'2.1.0+cu121'

## 1. DATA PREPARING AND LOADING

> Data can be almost anything .. in machine learning
>ML is a game of two parts
- get data into numerical representation
- Build a model to learn patterns in that numerical representation

we will use a linear regression formula to make a straight line with known **parameters**



In [4]:
##weight b bias a Y=A+BX
weight=0.7
bias=0.3
#create
start=0
end=1
step=0.02
#in ml X is tensor or matrix and x is vector
X=torch.arange(start,end,step)
y=weight*X + bias
X[:10],y[:10],len(X),len(y)

(tensor([0.0000, 0.0200, 0.0400, 0.0600, 0.0800, 0.1000, 0.1200, 0.1400, 0.1600,
         0.1800]),
 tensor([0.3000, 0.3140, 0.3280, 0.3420, 0.3560, 0.3700, 0.3840, 0.3980, 0.4120,
         0.4260]),
 50,
 50)

In [5]:
##weight b bias a Y=A+BX
weight=0.7
bias=0.3
#create
start=0
end=1
step=0.02
#in ml X is tensor or matrix and x is vector
X=torch.arange(start,end,step).unsqueeze(dim=1)
y=weight*X + bias
X[:10],y[:10],len(X),len(y)

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]),
 50,
 50)

### split data into training and test sets(one of the most important concepts of ml in general)
**three data sets**
> training set - model learns from this data,amount of data used is ~60-80%,always used

> validation set -model gets tuned,amount of data used is ~10-20%,often used

> test set-model gets evaluated on this data,amount of data used is ~10-20%,always used



In [11]:
#create a train/test split
train_split=(int(0.8*len(X)))
test_split=(int(0.2*len(y)))
train_split,test_split


(40, 10)

In [10]:
X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]
len(X_train), len(y_train), len(X_test), len(y_test)

(40, 40, 10, 10)

In [12]:
X_train,y_train

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800],
         [0.2000],
         [0.2200],
         [0.2400],
         [0.2600],
         [0.2800],
         [0.3000],
         [0.3200],
         [0.3400],
         [0.3600],
         [0.3800],
         [0.4000],
         [0.4200],
         [0.4400],
         [0.4600],
         [0.4800],
         [0.5000],
         [0.5200],
         [0.5400],
         [0.5600],
         [0.5800],
         [0.6000],
         [0.6200],
         [0.6400],
         [0.6600],
         [0.6800],
         [0.7000],
         [0.7200],
         [0.7400],
         [0.7600],
         [0.7800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260],
         [0.4400],
         [0.4540],
         [