<a href="https://colab.research.google.com/github/kavyareddy01/pytorchbirble/blob/main/pytorchbasicsday3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

**SELECTING DATA FROM TENSORS (INDEXING)**

In [2]:
##INDEXING WITH PYTORCH IS SIMILAR TO NUMPY
x=torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [3]:
x.shape

torch.Size([1, 3, 3])

In [4]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
#middle bracket
x[0][0]

tensor([1, 2, 3])

In [7]:
x[0,0]

tensor([1, 2, 3])

In [8]:
#inner bracket
x[0][0][0]

tensor(1)

In [9]:
x[0][1][1]

tensor(5)

In [10]:
x[0][0][1]

tensor(2)

In [11]:
##You can use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [12]:
x[:,:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
x[:,0,0]

tensor([1])

In [15]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [16]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [17]:
x[0,1,1]

tensor(5)

In [18]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
##index on x to return 9
x[0,2,2]

In [23]:
#index on x to return 3,6,9
x[0,:,2] #x[:,:,2]

tensor([3, 6, 9])

**PYTORCH** **AND** **NUMPY**


*   NumPy is a popular scientific python numerical computing library because of this pytorch has functionality to interact with it
*    data in NumPy ,want in pytorch tensor   
     torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
*   torch.Tensor.numpy() - PyTorch tensor -> NumPy array.



In [25]:
import numpy as np
array=np.arange(1.0,8.0)
t=torch.from_numpy(array)
array,t

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [26]:
array.dtype

dtype('float64')

In [27]:
torch.arange(1.0,8.0).dtype

torch.float32

* By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype
* However, many PyTorch calculations default to using float32.
* So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32).

In [50]:
import numpy as np
a=np.arange(1.0,8.0)
te=torch.from_numpy(a).type(torch.float32)
a,te,te.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [51]:
a= a + 1
a,te

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

if you change the array,tensor remains the same

In [52]:
##tensor to numpy
tensor=torch.ones(7)
numpy_t=tensor.numpy()
tensor,numpy_t

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [53]:
tensor.dtype,numpy_t.dtype

(torch.float32, dtype('float32'))

In [54]:
##change the tensor what happens to array
tensor=tensor+1
tensor,numpy_t

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

if you change the tensor,array remains the same