<a href="https://colab.research.google.com/github/kavyareddy01/pytorchbirble/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
print("I am wish to learn pytorch")

I am wish to learn pytorch


In [4]:
import torch
print(torch.__version__)

2.1.0+cu121


In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [6]:
#tensor
#scalar
s=torch.tensor(7)
s

tensor(7)

In [7]:

s.ndim

0

In [8]:
#get tensor back as python int
s.item()

7

In [9]:
#vector
v=torch.tensor([9,9])
v

tensor([9, 9])

In [10]:
v.ndim


1

In [11]:
v.shape

torch.Size([2])

In [12]:
##matrix
m=torch.tensor([[7,6],[9,8]])
m

tensor([[7, 6],
        [9, 8]])

In [13]:
m.shape


torch.Size([2, 2])

In [14]:
m.ndim


2

In [15]:
m[0]

tensor([7, 6])

In [16]:
m[1]

tensor([9, 8])

In [17]:
#tensor
t=torch.tensor([[[1,2,3],[2,3,4],[3,4,5]]])
t

tensor([[[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]]])

In [18]:
t.shape

torch.Size([1, 3, 3])

In [19]:
t.ndim

3

In [20]:
t[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [21]:
# @title Intro to tensors


In [22]:
t_rand=torch.rand(3,4)
t_rand

tensor([[0.2916, 0.6914, 0.5976, 0.4243],
        [0.6295, 0.2695, 0.9911, 0.1992],
        [0.4942, 0.1181, 0.2585, 0.5056]])

In [23]:
t_rand.ndim

2

In [24]:
rand_t=torch.rand(1,10,10)
rand_t

tensor([[[0.3572, 0.6249, 0.9125, 0.0426, 0.6306, 0.3866, 0.3924, 0.5114,
          0.1473, 0.0801],
         [0.2268, 0.8761, 0.7010, 0.4917, 0.7859, 0.5944, 0.5155, 0.5457,
          0.6364, 0.8459],
         [0.9146, 0.7153, 0.6781, 0.2656, 0.3809, 0.1150, 0.8364, 0.4923,
          0.2611, 0.1696],
         [0.0434, 0.3685, 0.5621, 0.7046, 0.4030, 0.9243, 0.7090, 0.3509,
          0.8111, 0.1308],
         [0.3765, 0.8450, 0.9693, 0.4625, 0.9139, 0.3770, 0.8949, 0.3051,
          0.4310, 0.0228],
         [0.6357, 0.6377, 0.5630, 0.9467, 0.9273, 0.5058, 0.5585, 0.2001,
          0.0105, 0.9324],
         [0.7129, 0.7695, 0.2736, 0.1151, 0.7761, 0.9407, 0.9261, 0.1821,
          0.6297, 0.1749],
         [0.0510, 0.4607, 0.5973, 0.2753, 0.4981, 0.5224, 0.3360, 0.0441,
          0.9848, 0.4598],
         [0.1399, 0.8922, 0.0459, 0.7699, 0.3657, 0.4569, 0.2861, 0.0268,
          0.9348, 0.5846],
         [0.0433, 0.0548, 0.6432, 0.3028, 0.3661, 0.4456, 0.0188, 0.9110,
          0.2133,

In [25]:
rand_t.ndim

3

In [26]:
r_i_s_tensor=torch.rand(size=(224,224,3))#height,width,color channels(R,G,B)
r_i_s_tensor.shape,r_i_s_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [27]:
r_i_s_tensor

tensor([[[0.5564, 0.7673, 0.2267],
         [0.7417, 0.5078, 0.3017],
         [0.2021, 0.4913, 0.1392],
         ...,
         [0.7838, 0.6112, 0.3679],
         [0.6572, 0.5099, 0.5228],
         [0.0149, 0.5696, 0.8441]],

        [[0.7945, 0.6168, 0.5684],
         [0.9680, 0.3667, 0.4403],
         [0.9926, 0.3665, 0.9300],
         ...,
         [0.5769, 0.1004, 0.8325],
         [0.7515, 0.0885, 0.6947],
         [0.5080, 0.9468, 0.3420]],

        [[0.6756, 0.8390, 0.1206],
         [0.3332, 0.0450, 0.2562],
         [0.7441, 0.3914, 0.1842],
         ...,
         [0.7986, 0.5057, 0.5071],
         [0.9809, 0.5619, 0.4292],
         [0.8841, 0.6287, 0.9229]],

        ...,

        [[0.8422, 0.3036, 0.7045],
         [0.2719, 0.5288, 0.5088],
         [0.1506, 0.4681, 0.1933],
         ...,
         [0.8818, 0.4799, 0.8610],
         [0.7017, 0.6207, 0.6815],
         [0.8717, 0.8332, 0.7824]],

        [[0.8038, 0.8835, 0.0734],
         [0.4361, 0.1607, 0.2239],
         [0.

In [28]:
torch.rand(3,3)

tensor([[0.3732, 0.9158, 0.7933],
        [0.1761, 0.9930, 0.5078],
        [0.6229, 0.3415, 0.3443]])

In [29]:
##zeros and ones tensors

z=torch.zeros(size=(3,4))
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
z*t_rand

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
o=torch.ones(size=(3,4))
o

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
o.dtype

torch.float32

In [33]:
rand_t.dtype

torch.float32

In [34]:
t_rand.dtype

torch.float32

In [35]:
z.dtype

torch.float32

In [36]:
##creating a range of tensors
torch.range(0,10)

<ipython-input-36-df6a2ff44385>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
torch.__version__

'2.1.0+cu121'

In [38]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
one_to_ten=torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
torch.arange(start=1,end=1000,step=77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [41]:
torch.arange(start=1,end=11,step=1)##end is exclusive

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
ten_0s=torch.zeros_like(input=one_to_ten)
ten_0s

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
##tensor datatypes

In [44]:
float_32_tensor=torch.tensor([3.0,5.0,10.0],dtype=None)
float_32_tensor

tensor([ 3.,  5., 10.])

In [46]:
float_32_tensor.dtype

torch.float32