<a href="https://colab.research.google.com/github/kavyareddy01/pytorchbirble/blob/main/day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##tensor datatypes

In [178]:
import torch
print(torch.__version__)

2.1.0+cu121


In [179]:
float_32_tensor=torch.tensor([3.0,5.0,10.0],dtype=None)
float_32_tensor

tensor([ 3.,  5., 10.])

In [180]:
float_32_tensor.dtype  ##default

torch.float32

In [181]:
float_32_t=torch.tensor([3.0,5.0,10.0],dtype=torch.float16)
float_32_t

tensor([ 3.,  5., 10.], dtype=torch.float16)

In [182]:
float_32_t.dtype

torch.float16

In [183]:
f=torch.tensor([1.0,2.0,3.0],dtype=None,# what datatype  is the tensor
                            device=None,#what device is ur tensor on
                            requires_grad=False  )#whether or not to track gradients with this tensors operatns
##tensor imp parameters
f
##32-bit floating point->torch.float or torch.float32
#64-bit floating point ->torch.float64 or torch.double
#16-bit floating point ->torch.float16 or torch.half

tensor([1., 2., 3.])

tensor datatypes are the 3 big errors you will run into with pytorch or deeplearning

* tensors not right datatype
* tensors not right shape
* tensors not on the right device

In [184]:
f_16_t=float_32_t.type(torch.float16)
f_16_t

tensor([ 3.,  5., 10.], dtype=torch.float16)

In [185]:
f_16_t*float_32_t

tensor([  9.,  25., 100.], dtype=torch.float16)

In [186]:
float_32_t*f_16_t

tensor([  9.,  25., 100.], dtype=torch.float16)

In [187]:
int_32_tensor=torch.tensor([1,3,6],dtype=torch.int32)
int_32_tensor

tensor([1, 3, 6], dtype=torch.int32)

In [188]:
float_32_t*int_32_tensor

tensor([ 3., 15., 60.], dtype=torch.float16)

In [189]:
int_64_tensor=torch.tensor([1,3,6],dtype=torch.int64)
int_64_tensor

tensor([1, 3, 6])

In [190]:
float_32_t*int_64_tensor

tensor([ 3., 15., 60.], dtype=torch.float16)

In [191]:
long=torch.tensor([4,5,6],dtype=torch.long)
long

tensor([4, 5, 6])

In [192]:
long*float_32_t

tensor([12., 25., 60.], dtype=torch.float16)

GETTING TENSOR ATTRIBUTES(INFO ABOUT TENSORS)

* tensors not right datatype=toget data type from tensor,can use 'tensor.dtype'

* tensors not right shape=to get shape of tensor,can use'tensor.shape'

* tensors not on the right device=to get device from a tensor,can use 'tensor.device'


In [193]:
##creating a tensor
some=torch.rand(3,4)
some

tensor([[0.6045, 0.5039, 0.5607, 0.2885],
        [0.5614, 0.8408, 0.6036, 0.0059],
        [0.6750, 0.1584, 0.3993, 0.4908]])

In [194]:
some.dtype

torch.float32

In [195]:
some.shape

torch.Size([3, 4])

In [196]:
some.device

device(type='cpu')

In [197]:
some.size()##function

torch.Size([3, 4])

In [198]:
print(some)
print(f"datatype of tensor : {some.dtype}")
print(f"size of tensor : {some.size()}")
print(f"shape of tensor : {some.shape}")
print(f"device of tensor : {some.device}")

tensor([[0.6045, 0.5039, 0.5607, 0.2885],
        [0.5614, 0.8408, 0.6036, 0.0059],
        [0.6750, 0.1584, 0.3993, 0.4908]])
datatype of tensor : torch.float32
size of tensor : torch.Size([3, 4])
shape of tensor : torch.Size([3, 4])
device of tensor : cpu


MANIPULATING TENSORS AND TENSORS OPERATNS tensor operatns include

* addition
* subtraction
* multiplicatn(element wise)
* division
* matrix multipilcatn


In [199]:
#create tensor
tensor=torch.tensor([2,3,4])
tensor+10

tensor([12, 13, 14])

In [200]:
tensor+100



tensor([102, 103, 104])

In [201]:
tensor*10

tensor([20, 30, 40])

In [202]:
tensor

tensor([2, 3, 4])

In [203]:
tensor-10

tensor([-8, -7, -6])

In [204]:
#pytorch in built functns
torch.mul(tensor,10)

tensor([20, 30, 40])

In [205]:
torch.add(tensor,120)

tensor([122, 123, 124])

There are two ways o performing matrix multiplicatn in neural networks and deeplearning
* element wise multiplicatn
* matrix Multiplictan(dot product)

In [206]:
# element wise
tensor*tensor

tensor([ 4,  9, 16])

In [207]:
print(tensor,"*",tensor)

tensor([2, 3, 4]) * tensor([2, 3, 4])


In [208]:
print(f"equals :{tensor*tensor}")

equals :tensor([ 4,  9, 16])


In [209]:
##matrix multiplication
torch.matmul(tensor,tensor) #2*2+3*3+4*4


tensor(29)

In [210]:
%%time
val=0
for i in range(len(tensor)):
    val+=tensor[i]*tensor[i]
print(val)

tensor(29)
CPU times: user 3.3 ms, sys: 0 ns, total: 3.3 ms
Wall time: 5.48 ms


In [211]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 78 µs, sys: 0 ns, total: 78 µs
Wall time: 84.9 µs


tensor(29)

In [212]:
tensor@tensor

tensor(29)

Two main rules of matrix multipilcation
* inner dimensions should match
     1.  '(4,5)@(4,5)' it don't work
     2.  '(4,5)@(5,4)' it works
* the resulting matrix has outer dimensions



In [213]:
torch.matmul(torch.rand(3,4),torch.rand(4,3))

tensor([[1.0419, 1.1895, 1.4195],
        [0.5323, 0.9184, 1.1135],
        [1.0428, 1.0639, 1.0222]])

In [214]:
torch.matmul(torch.rand(10,10),torch.rand(10,9)).shape

torch.Size([10, 9])

one of the most commom errors in deeplearning is shape errors

In [215]:
t1=torch.tensor([[1,2],[2,3],[3,4]])
t2=torch.tensor([[3,4],[4,5],[5,6]])
##torch.mm is same as torch.matmultiply
torch.mm(t1,t2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [216]:
t1.shape,t2.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [217]:
###to fix tensor shape issues we can manipulate one of the tensors using a **transpose**

### A **transpose** switches the axes or the dimensions of the given tensor  -->tensor.T  gives transpose of tensor

In [218]:
t2.T,t2

(tensor([[3, 4, 5],
         [4, 5, 6]]),
 tensor([[3, 4],
         [4, 5],
         [5, 6]]))

In [219]:
torch.matmul(t1,t2.T)

tensor([[11, 14, 17],
        [18, 23, 28],
        [25, 32, 39]])

In [220]:
t1.shape,t2.shape,t2.T.shape

(torch.Size([3, 2]), torch.Size([3, 2]), torch.Size([2, 3]))

In [221]:
print(f"Original shapes: t1 = {t1.shape}, t2 = {t2.shape}\n")
print(f"New shapes: t1= {t1.shape} (same as above), t2.T = {t2.T.shape}\n")
print(f"Multiplying: {t1.shape} * {t2.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(t1, t2.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: t1 = torch.Size([3, 2]), t2 = torch.Size([3, 2])

New shapes: t1= torch.Size([3, 2]) (same as above), t2.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[11, 14, 17],
        [18, 23, 28],
        [25, 32, 39]])

Output shape: torch.Size([3, 3])


Finding min ,max,sum,mean (TENSOR AGGREGATION)

In [222]:
## creating a tensor
t=torch.arange(0,100,10)
t

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [223]:
torch.min(t)

tensor(0)

In [224]:
t.min()

tensor(0)

In [225]:
t.max(),torch.max(t)

(tensor(90), tensor(90))

In [226]:
t.sum(),torch.sum(t)

(tensor(450), tensor(450))

In [227]:
t.mean(),torch.mean(t)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [228]:
t.dtype

torch.int64

In [229]:
torch.mean(t.type(torch.float32))

tensor(45.)

In [230]:
torch.mean(t.type(torch.float64))

tensor(45., dtype=torch.float64)

In [231]:
t.type(torch.float32).mean()   ### torch.mean() require tensors to be in torch.float32 (the most common) or another specific datatype, otherwise the operation will fail.

tensor(45.)

Finding the positional min max of the tensors

In [232]:
t

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [234]:
t.argmin()

tensor(0)

In [235]:
t[0]

tensor(0)

In [236]:
t.argmax()

tensor(9)

In [237]:
t[9]

tensor(90)

In [238]:
te=torch.arange(1,20,2)
te

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [239]:
te.argmin()

tensor(0)

In [241]:
te[0]

tensor(1)

In [242]:
te.argmax()

tensor(9)

In [243]:
te[9]

tensor(19)

Reshaping, viewing ,squeezing,unsqueezing and stacking tensors

* torch.reshape(input, shape): Reshapes input tensor toa desired shape (if compatible), can also use torch.Tensor.reshape().
* Tensor.view(shape): Returns a view of the original tensor in a different shape but shares the same data/memory as the original tensor.
* torch.stack(tensors, dim=0)	: Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size. combines multiple tensors on top of each other(vstack) or sidebyside(hstack)
* torch.squeeze(input): Squeezes input to remove all the dimenions with value 1.
* torch.unsqueeze(input, dim): Returns input with a dimension value of 1 added at dim.
* torch.permute(input, dims): Returns a view of the original input with its dimensions permuted (rearranged) to dims.

In [244]:
i=torch.arange(1.,10.)
i,i.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [245]:
#adding an extra dimension reshape
i_reshaped=i.reshape((1,7))
i_reshaped

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [246]:
i_reshaped=i.reshape((1,9))
i_reshaped,i_reshaped.size()

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [247]:
i_reshaped=i.reshape((9,1))
i_reshaped,i_reshaped.size()

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [248]:
i_reshaped=i.reshape((3,3))
i_reshaped,i_reshaped.size() ##the product dimensions of reshaped dimensions should be equal to product of original tensor dimensions

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [250]:
##change the view
j=i.view(1,9)
j,j.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [251]:
##changing j changes i(because a view of tensor shares the same memory as the original input tensor)

In [252]:
j[:,0]=5
j,i

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [253]:
##stack tensors on top of each other(vstack)
i_stacked=torch.stack([i, i, i, i],dim=0)
i_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [254]:
i_stacked=torch.stack([i, i, i, i],dim=1)
i_stacked


tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [255]:
#squeeze
i_reshaped

tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [256]:
i_reshaped.squeeze()

tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [257]:
i_reshaped.squeeze().shape

torch.Size([3, 3])

In [258]:
i_re=i.reshape((9,1))
i_re

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [259]:
i_re.size()

torch.Size([9, 1])

In [260]:
i_re.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [261]:
i_re.squeeze().shape

torch.Size([9])

In [263]:
print(f"Previous tensor: {i_re}")
print(f"Previous shape: {i_re.shape}")
i_squeezed = i_re.squeeze()
print(f"\nNew tensor: {i_squeezed}")
print(f"New shape: {i_squeezed.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [265]:
##torch.unsqueezed : adds 1 dimension to the target tensor at a specific dim

In [264]:
print(f"Previous tensor: {i_squeezed}")
print(f"Previous shape: {i_squeezed.shape}")

## Add an extra dimension with unsqueeze
i_unsqueezed = i_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {i_unsqueezed}")
print(f"New shape: {i_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [266]:
print(f"Previous tensor: {i_squeezed}")
print(f"Previous shape: {i_squeezed.shape}")

## Add an extra dimension with unsqueeze
i_unsqueezed = i_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {i_unsqueezed}")
print(f"New shape: {i_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [267]:
##torch.permute : rearranges the dimensions of the target tensor in a specified order

In [268]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [270]:
x_original[0,0,0]

tensor(0.8181)

In [272]:
x_original[0,0,0]=2463
x_permuted,x_permuted[0,0,0]

(tensor([[[2.4630e+03, 6.4032e-01, 3.1235e-02,  ..., 2.8527e-01,
           9.1820e-01, 3.1217e-01],
          [7.0017e-01, 9.6544e-01, 8.6462e-01,  ..., 1.4653e-01,
           2.3951e-01, 8.8124e-01],
          [3.6463e-01, 4.3844e-01, 4.9343e-01,  ..., 1.6117e-01,
           2.8174e-01, 6.2063e-01],
          ...,
          [7.3824e-01, 6.3467e-01, 4.0054e-01,  ..., 6.2200e-01,
           4.1861e-01, 3.7518e-01],
          [6.1521e-01, 5.4345e-02, 8.9197e-01,  ..., 5.5334e-01,
           2.4476e-01, 5.3556e-01],
          [6.0912e-01, 5.1097e-01, 3.9107e-01,  ..., 3.1746e-01,
           9.3268e-01, 6.0646e-03]],
 
         [[1.0024e-01, 9.3193e-02, 4.4521e-01,  ..., 4.8088e-01,
           8.7890e-03, 6.1797e-01],
          [6.9460e-01, 7.8901e-01, 8.4380e-01,  ..., 3.8756e-01,
           7.1310e-01, 2.9275e-01],
          [8.9063e-01, 2.3196e-01, 3.0441e-01,  ..., 2.1973e-01,
           6.1783e-01, 5.7664e-01],
          ...,
          [8.6794e-01, 9.9510e-01, 5.0926e-01,  ..., 5.579