<a href="https://colab.research.google.com/github/kavyareddy01/pytorchbirble/blob/main/pytorchbasicsday3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

**SELECTING DATA FROM TENSORS (INDEXING)**

In [2]:
##INDEXING WITH PYTORCH IS SIMILAR TO NUMPY
x=torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [3]:
x.shape

torch.Size([1, 3, 3])

In [4]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
#middle bracket
x[0][0]

tensor([1, 2, 3])

In [7]:
x[0,0]

tensor([1, 2, 3])

In [8]:
#inner bracket
x[0][0][0]

tensor(1)

In [9]:
x[0][1][1]

tensor(5)

In [10]:
x[0][0][1]

tensor(2)

In [11]:
##You can use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [12]:
x[:,:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
x[:,0,0]

tensor([1])

In [15]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [16]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [17]:
x[0,1,1]

tensor(5)

In [18]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
##index on x to return 9
x[0,2,2]

In [23]:
#index on x to return 3,6,9
x[0,:,2] #x[:,:,2]

tensor([3, 6, 9])

**PYTORCH** **AND** **NUMPY**


*   NumPy is a popular scientific python numerical computing library because of this pytorch has functionality to interact with it
*    data in NumPy ,want in pytorch tensor   
     torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
*   torch.Tensor.numpy() - PyTorch tensor -> NumPy array.



In [25]:
import numpy as np
array=np.arange(1.0,8.0)
t=torch.from_numpy(array)
array,t

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [26]:
array.dtype

dtype('float64')

In [27]:
torch.arange(1.0,8.0).dtype

torch.float32

* By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype
* However, many PyTorch calculations default to using float32.
* So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32).

In [50]:
import numpy as np
a=np.arange(1.0,8.0)
te=torch.from_numpy(a).type(torch.float32)
a,te,te.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [51]:
a= a + 1
a,te

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

if you change the array,tensor remains the same

In [52]:
##tensor to numpy
tensor=torch.ones(7)
numpy_t=tensor.numpy()
tensor,numpy_t

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [53]:
tensor.dtype,numpy_t.dtype

(torch.float32, dtype('float32'))

In [54]:
##change the tensor what happens to array
tensor=tensor+1
tensor,numpy_t

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

if you change the tensor,array remains the same

**REPRODUCIBILITY**
in short how a neural network learns :
* start with random numbers -> tensor operations ->update random numbers to try and make them better representations of data->again->again->again
* to reduce randomness in neural network and pytorch comes the concept of **random seed**.
* essentially what random seed does is "flavour" the randomness.


In [57]:
##trying to take the random out of random
torch.rand(3,3)

tensor([[0.6284, 0.0936, 0.4289],
        [0.3150, 0.2216, 0.1679],
        [0.8223, 0.8781, 0.6060]])

In [58]:
#create two random tensor
t1=torch.rand(3,4)
t2=torch.rand(3,4)
print(t1)
print(t2)
print(t1==t2)

tensor([[0.9981, 0.5051, 0.6652, 0.7584],
        [0.0234, 0.3372, 0.4695, 0.5622],
        [0.5130, 0.8025, 0.0732, 0.0311]])
tensor([[0.8184, 0.0623, 0.8087, 0.4353],
        [0.3034, 0.9578, 0.7287, 0.5003],
        [0.7878, 0.4279, 0.7749, 0.2312]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


The tensors come out with different values.

But what if we wanted to created two random tensors with the same values.

As in, the tensors would still contain random values but they would be of the same flavour.

That's where torch.manual_seed(seed) comes in, where seed is an integer (like 42 but it could be anything) that flavours the randomness.



In [60]:
random_seed=43
torch.manual_seed(random_seed)
t3=torch.rand(3,4)
t4=torch.rand(3,4)
t3,t4,t3==t4

(tensor([[0.4540, 0.1965, 0.9210, 0.3462],
         [0.1481, 0.0858, 0.5909, 0.0659],
         [0.7476, 0.6253, 0.9392, 0.1338]]),
 tensor([[0.5191, 0.5335, 0.5375, 0.7058],
         [0.4275, 0.2761, 0.8396, 0.1563],
         [0.1072, 0.7261, 0.3241, 0.8892]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [61]:
random_seed=43
torch.manual_seed(random_seed)
t3=torch.rand(3,4)
torch.manual_seed(random_seed)

t4=torch.rand(3,4)
t3,t4,t3==t4

(tensor([[0.4540, 0.1965, 0.9210, 0.3462],
         [0.1481, 0.0858, 0.5909, 0.0659],
         [0.7476, 0.6253, 0.9392, 0.1338]]),
 tensor([[0.4540, 0.1965, 0.9210, 0.3462],
         [0.1481, 0.0858, 0.5909, 0.0659],
         [0.7476, 0.6253, 0.9392, 0.1338]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

**ACCESSING** **TO** **GPUs**

Running tensors and pytorch objs o the gpus(and making the faster computations)
GPUs = faster computations of numbers ,thanks to nvidia h/w+cuda+pytorch working behind the scenes to make everything hunky

Method	Difficulty to setup	Pros	Cons	How to setup
* Google Colab ::	Easy	Free to use, almost zero setup required, can share work with others as easy as a link	Doesn't save your data outputs, limited compute, subject to timeouts	Follow the Google Colab Guide
* Use your own	Medium::Run everything locally on your own machine	GPUs aren't free, require upfront cost	Follow the PyTorch installation guidelines
* Cloud computing (AWS, GCP, Azure): Medium-Hard	Small upfront cost, access to almost infinite compute	Can get expensive if running continually, takes some time to setup right	Follow the PyTorch installation guidelines


In [2]:
!nvidia-smi


Sun Feb 11 12:31:35 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [1]:
#check for gpu access with pytorch
import torch
torch.cuda.is_available()

True

In [3]:
#setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
#count no of devices
torch.cuda.device_count()

1

In [ ]:
##3.putting tensors (and models) on the GPU
#the reason we want our tensors or models on the gpu is that gpu results in faster computation

In [5]:
#create a tensor and the default ion the cpu
t=torch.tensor([1,2,3])
#tensor not on the gpu
print(t,t.device)

tensor([1, 2, 3]) cpu


In [6]:
t_on_gpu=t.to(device)
t_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [7]:
##moving tensors back to the cpu
t_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [8]:
t_on_cpu=t_on_gpu.cpu()
t_on_cpu.numpy()

array([1, 2, 3])

In [9]:
t_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [10]:
##creating a random tensor of shape(7,7
torch.rand(7,7)

tensor([[1.1712e-02, 5.2730e-01, 5.2093e-01, 4.0999e-01, 9.5788e-01, 4.5478e-04,
         1.0881e-01],
        [2.5095e-01, 7.3971e-01, 5.8482e-02, 1.6019e-02, 4.1569e-01, 1.3043e-01,
         4.8200e-01],
        [8.6738e-01, 6.9274e-01, 6.7350e-01, 2.5896e-01, 9.3997e-01, 9.8847e-01,
         3.6005e-01],
        [1.3693e-01, 2.9776e-02, 2.6372e-01, 2.5454e-01, 5.4644e-01, 4.8215e-01,
         6.3942e-01],
        [3.2044e-01, 7.8399e-02, 4.5399e-01, 8.7992e-01, 1.7378e-01, 9.0416e-02,
         6.5022e-01],
        [9.4676e-01, 9.1449e-02, 1.7086e-01, 4.1124e-01, 5.0517e-01, 8.5114e-01,
         8.6543e-01],
        [6.9665e-01, 5.6359e-01, 2.5244e-01, 8.8188e-01, 5.4416e-01, 9.8576e-01,
         7.8809e-02]])

In [11]:
#Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
torch.matmul(torch.rand(7,7),torch.rand(1,7).T)

tensor([[1.7408],
        [2.1890],
        [2.9920],
        [1.7926],
        [1.5739],
        [2.1797],
        [1.6262]])

In [14]:
##Set the random seed to 0 and do exercises 2 & 3 over again.

random_seed=0
torch.manual_seed(random_seed)
print(torch.rand(7,7))

torch.manual_seed(random_seed)
torch.matmul(torch.rand(7,7),torch.rand(1,7).T)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])