<a href="https://colab.research.google.com/github/kavyareddy01/pytorchbirble/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("I am wish to learn pytorch")

I am wish to learn pytorch


In [ ]:
import torch
print(torch.__version__)

2.1.0+cu121


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [ ]:
#tensor
#scalar
s=torch.tensor(7)
s

tensor(7)

In [ ]:

s.ndim

0

In [ ]:
#get tensor back as python int
s.item()

7

In [ ]:
#vector
v=torch.tensor([9,9])
v

tensor([9, 9])

In [ ]:
v.ndim


1

In [ ]:
v.shape

torch.Size([2])

In [ ]:
##matrix
m=torch.tensor([[7,6],[9,8]])
m

tensor([[7, 6],
        [9, 8]])

In [ ]:
m.shape


torch.Size([2, 2])

In [ ]:
m.ndim


2

In [ ]:
m[0]

tensor([7, 6])

In [ ]:
m[1]

tensor([9, 8])

In [ ]:
#tensor
t=torch.tensor([[[1,2,3],[2,3,4],[3,4,5]]])
t

tensor([[[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]]])

In [ ]:
t.shape

torch.Size([1, 3, 3])

In [ ]:
t.ndim

3

In [ ]:
t[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [ ]:
# @title Intro to tensors


In [ ]:
t_rand=torch.rand(3,4)
t_rand

tensor([[0.6734, 0.7181, 0.1712, 0.3746],
        [0.8599, 0.3625, 0.9391, 0.7848],
        [0.8220, 0.7742, 0.8350, 0.4972]])

In [ ]:
t_rand.ndim

2

In [ ]:
rand_t=torch.rand(1,10,10)
rand_t

tensor([[[0.3890, 0.6274, 0.6425, 0.8736, 0.8091, 0.5818, 0.8988, 0.8671,
          0.4705, 0.7941],
         [0.2146, 0.4576, 0.6814, 0.8031, 0.7966, 0.1173, 0.0045, 0.1644,
          0.3520, 0.5478],
         [0.3765, 0.7138, 0.0132, 0.1979, 0.0895, 0.1133, 0.3061, 0.8483,
          0.3072, 0.4127],
         [0.3601, 0.3008, 0.1792, 0.9773, 0.1733, 0.7485, 0.9635, 0.5120,
          0.8196, 0.7564],
         [0.3506, 0.6968, 0.4193, 0.8340, 0.2046, 0.8453, 0.1787, 0.1840,
          0.3607, 0.6391],
         [0.4594, 0.3171, 0.7603, 0.6392, 0.6772, 0.6950, 0.0229, 0.5605,
          0.1020, 0.3613],
         [0.0477, 0.8037, 0.0765, 0.6265, 0.8541, 0.2248, 0.0927, 0.1847,
          0.9977, 0.2084],
         [0.3207, 0.3012, 0.8704, 0.2646, 0.2652, 0.5275, 0.0256, 0.8781,
          0.9560, 0.9621],
         [0.2181, 0.4497, 0.8696, 0.2289, 0.5241, 0.5541, 0.3607, 0.8884,
          0.3757, 0.2943],
         [0.0392, 0.0114, 0.9391, 0.3116, 0.4754, 0.3870, 0.9540, 0.1096,
          0.7775,

In [ ]:
rand_t.ndim

3

In [ ]:
r_i_s_tensor=torch.rand(size=(224,224,3))#height,width,color channels(R,G,B)
r_i_s_tensor.shape,r_i_s_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
r_i_s_tensor

tensor([[[0.4887, 0.3384, 0.3654],
         [0.1327, 0.3470, 0.0411],
         [0.1727, 0.4162, 0.8218],
         ...,
         [0.3496, 0.1617, 0.2359],
         [0.9414, 0.8693, 0.0399],
         [0.7075, 0.4039, 0.0749]],

        [[0.9895, 0.8030, 0.7554],
         [0.8873, 0.0787, 0.6796],
         [0.3287, 0.1678, 0.7919],
         ...,
         [0.1520, 0.2026, 0.1618],
         [0.0047, 0.1710, 0.7314],
         [0.4373, 0.2121, 0.3459]],

        [[0.7474, 0.3293, 0.4797],
         [0.0411, 0.1937, 0.1920],
         [0.0754, 0.4485, 0.6047],
         ...,
         [0.8398, 0.2579, 0.0656],
         [0.3541, 0.8849, 0.3556],
         [0.6940, 0.6245, 0.5079]],

        ...,

        [[0.8852, 0.1025, 0.9551],
         [0.3964, 0.2277, 0.0873],
         [0.3818, 0.1083, 0.9772],
         ...,
         [0.7076, 0.7822, 0.0454],
         [0.6336, 0.8646, 0.6740],
         [0.9885, 0.9397, 0.6052]],

        [[0.9674, 0.6431, 0.2607],
         [0.0364, 0.4265, 0.8216],
         [0.