<a href="https://colab.research.google.com/github/kavyareddy01/pytorchbirble/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("I am wish to learn pytorch")

I am wish to learn pytorch


In [2]:
import torch
print(torch.__version__)

2.1.0+cu121


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [22]:
#tensor
#scalar
s=torch.tensor(7)
s

tensor(7)

In [23]:

s.ndim

0

In [9]:
#get tensor back as python int
s.item()

7

In [10]:
#vector
v=torch.tensor([9,9])
v

tensor([9, 9])

In [11]:
v.ndim


1

In [14]:
v.shape

torch.Size([2])

In [15]:
##matrix
m=torch.tensor([[7,6],[9,8]])
m

tensor([[7, 6],
        [9, 8]])

In [16]:
m.shape


torch.Size([2, 2])

In [24]:
m.ndim


2

In [25]:
m[0]

tensor([7, 6])

In [26]:
m[1]

tensor([9, 8])

In [27]:
#tensor
t=torch.tensor([[[1,2,3],[2,3,4],[3,4,5]]])
t

tensor([[[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]]])

In [28]:
t.shape

torch.Size([1, 3, 3])

In [29]:
t.ndim

3